<?xml version="1.0" encoding="utf-8"?><Database Name="MBBS" Class="MBBSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SINDY-PC\SARAI;Initial Catalog=MBBS;Integrated Security=True" SettingsObjectName="Misión.My.MySettings" SettingsPropertyName="MBBSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Adopcion" Member="Adopcions">
    <Type Name="Adopcion">
      <Column Name="IdAdopcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaAdopcion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSponsor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoPagoAdopcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoAdopcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Adopcion_AdopcionPago" Member="AdopcionPagos" ThisKey="IdAdopcion" OtherKey="Idadopcion" Type="AdopcionPago" />
      <Association Name="Adopcion_Carta" Member="Cartas" ThisKey="IdAdopcion" OtherKey="IdAdopcion" Type="Carta" />
      <Association Name="Adopcion_Ofrenda" Member="Ofrendas" ThisKey="IdAdopcion" OtherKey="IdAdopcion" Type="Ofrenda" />
      <Association Name="Beneficiado_Adopcion" Member="Beneficiado" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="Beneficiado" IsForeignKey="true" />
      <Association Name="EstadoAdopcion_Adopcion" Member="EstadoAdopcion" ThisKey="IdEstadoAdopcion" OtherKey="IdEstadoAdopcion" Type="EstadoAdopcion" IsForeignKey="true" />
      <Association Name="Sponsor_Adopcion" Member="Sponsor" ThisKey="IdSponsor" OtherKey="IdSponsor" Type="Sponsor" IsForeignKey="true" />
      <Association Name="TipoPagoAdopcion_Adopcion" Member="TipoPagoAdopcion" ThisKey="IdTipoPagoAdopcion" OtherKey="IdTipoPagoAdopcion" Type="TipoPagoAdopcion" IsForeignKey="true" />
      <Association Name="Usuario_Adopcion" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdopcionPago" Member="AdopcionPagos">
    <Type Name="AdopcionPago">
      <Column Name="IdAdopcionPago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Valor" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Idadopcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Adopcion_AdopcionPago" Member="Adopcion" ThisKey="Idadopcion" OtherKey="IdAdopcion" Type="Adopcion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AuditoriaLog" Member="AuditoriaLogs">
    <Type Name="AuditoriaLog">
      <Column Name="IdLog" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_AuditoriaLog" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Beneficiado" Member="Beneficiados">
    <Type Name="Beneficiado">
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombreBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CantidadHermanos" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CantidadHermanas" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ColorOjos" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ColorPelo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IdGradoCursado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSexo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdIglesia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLugar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoBeneficiado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdInstitucion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Interno" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AsistenciaClaseDominical" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdNacionalidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEnfermedadPadecimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaHistotiaEnviada" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Beneficiado_Adopcion" Member="Adopcions" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="Adopcion" />
      <Association Name="Beneficiado_CasaBeneficiado" Member="CasaBeneficiados" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="CasaBeneficiado" />
      <Association Name="Beneficiado_InteresesBeneficiado" Member="InteresesBeneficiados" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="InteresesBeneficiado" />
      <Association Name="EnfermedadPadecimiento_Beneficiado" Member="EnfermedadPadecimiento" ThisKey="IdEnfermedadPadecimiento" OtherKey="IdEnfermedadPadecimiento" Type="EnfermedadPadecimiento" IsForeignKey="true" />
      <Association Name="EstadoBeneficiado_Beneficiado" Member="EstadoBeneficiado" ThisKey="IdEstadoBeneficiado" OtherKey="IdEstadoBeneficiado" Type="EstadoBeneficiado" IsForeignKey="true" />
      <Association Name="GradoCursado_Beneficiado" Member="GradoCursado" ThisKey="IdGradoCursado" OtherKey="IdGradoCursado" Type="GradoCursado" IsForeignKey="true" />
      <Association Name="Iglesia_Beneficiado" Member="Iglesia" ThisKey="IdIglesia" OtherKey="IdIglesia" Type="Iglesia" IsForeignKey="true" />
      <Association Name="Institucion_Beneficiado" Member="Institucion" ThisKey="IdInstitucion" OtherKey="IdInstitucion" Type="Institucion" IsForeignKey="true" />
      <Association Name="Lugar_Beneficiado" Member="Lugar" ThisKey="IdLugar" OtherKey="IdLugar" Type="Lugar" IsForeignKey="true" />
      <Association Name="Nacionalidad_Beneficiado" Member="Nacionalidad" ThisKey="IdNacionalidad" OtherKey="IdNacionalidad" Type="Nacionalidad" IsForeignKey="true" />
      <Association Name="Sexo_Beneficiado" Member="Sexo" ThisKey="IdSexo" OtherKey="IdSexo" Type="Sexo" IsForeignKey="true" />
      <Association Name="Usuario_Beneficiado" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BeneficiadoHermano" Member="BeneficiadoHermanos">
    <Type Name="BeneficiadoHermano">
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdHermano" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BeneficiadoTutor" Member="BeneficiadoTutors">
    <Type Name="BeneficiadoTutor">
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdTutor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cartas" Member="Cartas">
    <Type Name="Carta">
      <Column Name="IdCarta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Remitente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Destinatario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoCarta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdAdopcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Adopcion_Carta" Member="Adopcion" ThisKey="IdAdopcion" OtherKey="IdAdopcion" Type="Adopcion" IsForeignKey="true" />
      <Association Name="RemitenteDestinatario_Carta" Member="RemitenteDestinatario" ThisKey="Destinatario" OtherKey="IdRemitenteDestinatario" Type="RemitenteDestinatario" IsForeignKey="true" />
      <Association Name="RemitenteDestinatario_Carta1" Member="RemitenteDestinatario1" ThisKey="Remitente" OtherKey="IdRemitenteDestinatario" Type="RemitenteDestinatario" IsForeignKey="true" />
      <Association Name="TipoCarta_Carta" Member="TipoCarta" ThisKey="IdTipoCarta" OtherKey="IdTipoCarta" Type="TipoCarta" IsForeignKey="true" />
      <Association Name="Usuario_Carta" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CasaBeneficiado" Member="CasaBeneficiados">
    <Type Name="CasaBeneficiado">
      <Column Name="IdCasaBeneficiado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CantidadDormitorios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadCamas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadHamacas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRopaCama" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadMesas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadSillas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Piso" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoCasa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Beneficiado_CasaBeneficiado" Member="Beneficiado" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="Beneficiado" IsForeignKey="true" />
      <Association Name="TipoCasa_CasaBeneficiado" Member="TipoCasa" ThisKey="IdTipoCasa" OtherKey="IdTipoCasa" Type="TipoCasa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EnfermedadPadecimiento" Member="EnfermedadPadecimientos">
    <Type Name="EnfermedadPadecimiento">
      <Column Name="IdEnfermedadPadecimiento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnfermedadPadecimiento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EnfermedadPadecimiento_Beneficiado" Member="Beneficiados" ThisKey="IdEnfermedadPadecimiento" OtherKey="IdEnfermedadPadecimiento" Type="Beneficiado" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoAdopcion" Member="EstadoAdopcions">
    <Type Name="EstadoAdopcion">
      <Column Name="IdEstadoAdopcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstadoAdopcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EstadoAdopcion_Adopcion" Member="Adopcions" ThisKey="IdEstadoAdopcion" OtherKey="IdEstadoAdopcion" Type="Adopcion" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoBeneficiado" Member="EstadoBeneficiados">
    <Type Name="EstadoBeneficiado">
      <Column Name="IdEstadoBeneficiado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstadoBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EstadoBeneficiado_Beneficiado" Member="Beneficiados" ThisKey="IdEstadoBeneficiado" OtherKey="IdEstadoBeneficiado" Type="Beneficiado" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoUsuario" Member="EstadoUsuarios">
    <Type Name="EstadoUsuario">
      <Column Name="IdEstadoUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstadoUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EstadoUsuario_Usuario" Member="Usuarios" ThisKey="IdEstadoUsuario" OtherKey="IdEstadoUsuario" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.GradoCursado" Member="GradoCursados">
    <Type Name="GradoCursado">
      <Column Name="IdGradoCursado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GradoCursado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GradoCursado_Beneficiado" Member="Beneficiados" ThisKey="IdGradoCursado" OtherKey="IdGradoCursado" Type="Beneficiado" />
      <Association Name="GradoCursado_Hermano" Member="Hermanos" ThisKey="IdGradoCursado" OtherKey="IdGradoCursado" Type="Hermano" />
    </Type>
  </Table>
  <Table Name="dbo.Hermano" Member="Hermanos">
    <Type Name="Hermano">
      <Column Name="IdHermano" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreHermano" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoHermano" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SponsorHermano" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdGradoCursado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSexo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GradoCursado_Hermano" Member="GradoCursado" ThisKey="IdGradoCursado" OtherKey="IdGradoCursado" Type="GradoCursado" IsForeignKey="true" />
      <Association Name="Sexo_Hermano" Member="Sexo" ThisKey="IdSexo" OtherKey="IdSexo" Type="Sexo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Iglesia" Member="Iglesias">
    <Type Name="Iglesia">
      <Column Name="IdIglesia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Iglesia" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NombrePastor" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Iglesia_Beneficiado" Member="Beneficiados" ThisKey="IdIglesia" OtherKey="IdIglesia" Type="Beneficiado" />
      <Association Name="Iglesia_Tutor" Member="Tutors" ThisKey="IdIglesia" OtherKey="IdIglesia" Type="Tutor" />
    </Type>
  </Table>
  <Table Name="dbo.Institucion" Member="Institucions">
    <Type Name="Institucion">
      <Column Name="IdInstitucion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Institucion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoInstitucion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Institucion_Beneficiado" Member="Beneficiados" ThisKey="IdInstitucion" OtherKey="IdInstitucion" Type="Beneficiado" />
      <Association Name="TipoInstitucion_Institucion" Member="TipoInstitucion" ThisKey="IdTipoInstitucion" OtherKey="IdTipoInstitucion" Type="TipoInstitucion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InteresesBeneficiado" Member="InteresesBeneficiados">
    <Type Name="InteresesBeneficiado">
      <Column Name="IdIntereseBeneficiado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GustaComerBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GustaJugarBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GustaTenerBeneficiado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdBeneficiado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Beneficiado_InteresesBeneficiado" Member="Beneficiado" ThisKey="IdBeneficiado" OtherKey="IdBeneficiado" Type="Beneficiado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lugar" Member="Lugars">
    <Type Name="Lugar">
      <Column Name="IdLugar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lugar" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdPais" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lugar_Beneficiado" Member="Beneficiados" ThisKey="IdLugar" OtherKey="IdLugar" Type="Beneficiado" />
      <Association Name="Lugar_Tutor" Member="Tutors" ThisKey="IdLugar" OtherKey="IdLugar" Type="Tutor" />
      <Association Name="Pai_Lugar" Member="Pai" ThisKey="IdPais" OtherKey="IdPais" Type="Pai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nacionalidad" Member="Nacionalidads">
    <Type Name="Nacionalidad">
      <Column Name="IdNacionalidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nacionalidad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Nacionalidad_Beneficiado" Member="Beneficiados" ThisKey="IdNacionalidad" OtherKey="IdNacionalidad" Type="Beneficiado" />
    </Type>
  </Table>
  <Table Name="dbo.OficioProfesion" Member="OficioProfesions">
    <Type Name="OficioProfesion">
      <Column Name="IdOficioProfesion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OficioProfesion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="OficioProfesion_Tutor" Member="Tutors" ThisKey="IdOficioProfesion" OtherKey="IdOficioProfesion" Type="Tutor" />
    </Type>
  </Table>
  <Table Name="dbo.Ofrenda" Member="Ofrendas">
    <Type Name="Ofrenda">
      <Column Name="IdOfrenda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaRecibida" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fechaEntregado" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionOfrenda" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoOfrenda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdAdopcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Adopcion_Ofrenda" Member="Adopcion" ThisKey="IdAdopcion" OtherKey="IdAdopcion" Type="Adopcion" IsForeignKey="true" />
      <Association Name="TipoOfrenda_Ofrenda" Member="TipoOfrenda" ThisKey="IdTipoOfrenda" OtherKey="IdTipoOfrenda" Type="TipoOfrenda" IsForeignKey="true" />
      <Association Name="Usuario_Ofrenda" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pais" Member="Pais">
    <Type Name="Pai">
      <Column Name="IdPais" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pais" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pai_Lugar" Member="Lugars" ThisKey="IdPais" OtherKey="IdPais" Type="Lugar" />
      <Association Name="Pai_Sponsor" Member="Sponsors" ThisKey="IdPais" OtherKey="IdPais" Type="Sponsor" />
    </Type>
  </Table>
  <Table Name="dbo.Parentesco" Member="Parentescos">
    <Type Name="Parentesco">
      <Column Name="IdParentesco" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Parentesco" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Parentesco_Tutor" Member="Tutors" ThisKey="IdParentesco" OtherKey="IdParentesco" Type="Tutor" />
    </Type>
  </Table>
  <Table Name="dbo.RemitenteDestinatario" Member="RemitenteDestinatarios">
    <Type Name="RemitenteDestinatario">
      <Column Name="IdRemitenteDestinatario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RemitenteDestinatario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RemitenteDestinatario_Carta" Member="Cartas" ThisKey="IdRemitenteDestinatario" OtherKey="Destinatario" Type="Carta" />
      <Association Name="RemitenteDestinatario_Carta1" Member="Cartas1" ThisKey="IdRemitenteDestinatario" OtherKey="Remitente" Type="Carta" />
    </Type>
  </Table>
  <Table Name="dbo.Sexo" Member="Sexos">
    <Type Name="Sexo">
      <Column Name="IdSexo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sexo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Sexo_Beneficiado" Member="Beneficiados" ThisKey="IdSexo" OtherKey="IdSexo" Type="Beneficiado" />
      <Association Name="Sexo_Hermano" Member="Hermanos" ThisKey="IdSexo" OtherKey="IdSexo" Type="Hermano" />
      <Association Name="Sexo_Sponsor" Member="Sponsors" ThisKey="IdSexo" OtherKey="IdSexo" Type="Sponsor" />
      <Association Name="Sexo_Tutor" Member="Tutors" ThisKey="IdSexo" OtherKey="IdSexo" Type="Tutor" />
    </Type>
  </Table>
  <Table Name="dbo.Sponsor" Member="Sponsors">
    <Type Name="Sponsor">
      <Column Name="IdSponsor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombreCompletoSponsor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdSexo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPais" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoSponsor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sponsor_Adopcion" Member="Adopcions" ThisKey="IdSponsor" OtherKey="IdSponsor" Type="Adopcion" />
      <Association Name="Pai_Sponsor" Member="Pai" ThisKey="IdPais" OtherKey="IdPais" Type="Pai" IsForeignKey="true" />
      <Association Name="Sexo_Sponsor" Member="Sexo" ThisKey="IdSexo" OtherKey="IdSexo" Type="Sexo" IsForeignKey="true" />
      <Association Name="TipoSponsor_Sponsor" Member="TipoSponsor" ThisKey="IdTipoSponsor" OtherKey="IdTipoSponsor" Type="TipoSponsor" IsForeignKey="true" />
      <Association Name="Usuario_Sponsor" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoCarta" Member="TipoCartas">
    <Type Name="TipoCarta">
      <Column Name="IdTipoCarta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoCarta" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoCarta_Carta" Member="Cartas" ThisKey="IdTipoCarta" OtherKey="IdTipoCarta" Type="Carta" />
    </Type>
  </Table>
  <Table Name="dbo.TipoCasa" Member="TipoCasas">
    <Type Name="TipoCasa">
      <Column Name="IdTipoCasa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoCasa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoCasa_CasaBeneficiado" Member="CasaBeneficiados" ThisKey="IdTipoCasa" OtherKey="IdTipoCasa" Type="CasaBeneficiado" />
    </Type>
  </Table>
  <Table Name="dbo.TipoInstitucion" Member="TipoInstitucions">
    <Type Name="TipoInstitucion">
      <Column Name="IdTipoInstitucion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoInstitucion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoInstitucion_Institucion" Member="Institucions" ThisKey="IdTipoInstitucion" OtherKey="IdTipoInstitucion" Type="Institucion" />
    </Type>
  </Table>
  <Table Name="dbo.TipoOfrenda" Member="TipoOfrendas">
    <Type Name="TipoOfrenda">
      <Column Name="IdTipoOfrenda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoOfrenda" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoOfrenda_Ofrenda" Member="Ofrendas" ThisKey="IdTipoOfrenda" OtherKey="IdTipoOfrenda" Type="Ofrenda" />
    </Type>
  </Table>
  <Table Name="dbo.TipoPagoAdopcion" Member="TipoPagoAdopcions">
    <Type Name="TipoPagoAdopcion">
      <Column Name="IdTipoPagoAdopcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoPagoAdopcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoPagoAdopcion_Adopcion" Member="Adopcions" ThisKey="IdTipoPagoAdopcion" OtherKey="IdTipoPagoAdopcion" Type="Adopcion" />
    </Type>
  </Table>
  <Table Name="dbo.TipoSponsor" Member="TipoSponsors">
    <Type Name="TipoSponsor">
      <Column Name="IdTipoSponsor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoSponsor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoSponsor_Sponsor" Member="Sponsors" ThisKey="IdTipoSponsor" OtherKey="IdTipoSponsor" Type="Sponsor" />
    </Type>
  </Table>
  <Table Name="dbo.Tutor" Member="Tutors">
    <Type Name="Tutor">
      <Column Name="IdTutor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreTutor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoTutor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SalarioDia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IdOficioProfesion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSexo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdIglesia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLugar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdParentesco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Iglesia_Tutor" Member="Iglesia" ThisKey="IdIglesia" OtherKey="IdIglesia" Type="Iglesia" IsForeignKey="true" />
      <Association Name="Lugar_Tutor" Member="Lugar" ThisKey="IdLugar" OtherKey="IdLugar" Type="Lugar" IsForeignKey="true" />
      <Association Name="OficioProfesion_Tutor" Member="OficioProfesion" ThisKey="IdOficioProfesion" OtherKey="IdOficioProfesion" Type="OficioProfesion" IsForeignKey="true" />
      <Association Name="Parentesco_Tutor" Member="Parentesco" ThisKey="IdParentesco" OtherKey="IdParentesco" Type="Parentesco" IsForeignKey="true" />
      <Association Name="Sexo_Tutor" Member="Sexo" ThisKey="IdSexo" OtherKey="IdSexo" Type="Sexo" IsForeignKey="true" />
      <Association Name="Usuario_Tutor" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Adopcion" Member="Adopcions" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Adopcion" />
      <Association Name="Usuario_AuditoriaLog" Member="AuditoriaLogs" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="AuditoriaLog" />
      <Association Name="Usuario_Beneficiado" Member="Beneficiados" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Beneficiado" />
      <Association Name="Usuario_Carta" Member="Cartas" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Carta" />
      <Association Name="Usuario_Ofrenda" Member="Ofrendas" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Ofrenda" />
      <Association Name="Usuario_Sponsor" Member="Sponsors" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Sponsor" />
      <Association Name="Usuario_Tutor" Member="Tutors" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Tutor" />
      <Association Name="EstadoUsuario_Usuario" Member="EstadoUsuario" ThisKey="IdEstadoUsuario" OtherKey="IdEstadoUsuario" Type="EstadoUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Sp_ExisteUsuario" Method="Sp_ExisteUsuario">
    <Parameter Name="NombreUsuario" Parameter="nombreUsuario" Type="System.String" DbType="NVarChar(25)" />
    <Parameter Name="Contraseña" Parameter="contraseña" Type="System.String" DbType="NVarChar(40)" />
    <ElementType Name="Sp_ExisteUsuarioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MostrarID" Method="sp_MostrarID">
    <Parameter Name="nombreusuario" Type="System.String" DbType="VarChar(25)" />
    <ElementType Name="sp_MostrarIDResult">
      <Column Name="nombreusuario" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>